### ISSUE TITLE
Rules Request - Enum Reason Values

### ISSUE THREAD

**Issue by d-wasserman** [sharedstreets/curblr#13]
Is it possible to get this to be a more standardized set of values? I think it is fine to be optional, but it is not clear when and how these should be used as specified. I feel like they should be enum values with little flexibility because they really enable this specification to clarify more complex rules. Is there a way to be a little more rigid on reasons? 

I am really concerned about this being scaled up and everyone does not use the suggested values on these items. 

Document being referenced: 
https://github.com/sharedstreets/curblr/blob/master/Rule.md

**Comment by emilyeros** [comment]
Reason has been removed as part of the overhaul oof how we handle overlapping rules and priority levels (https://github.com/sharedstreets/curblr/pull/21). It became redundant and superfluous with other fields.
