### ISSUE TITLE
License to Use

### ISSUE THREAD

**Issue by d-wasserman** [sharedstreets/curblr#14]
What formal license govern's CurbLR and the specification? Is it similar to GTFS or SharedStreets Ref Spec? Apache 2.0? MIT? 

Without one, it it is hard to build on explicitly, or at least has uncertainty attached to it SharedStreets may not intend.

**Comment by emilyeros** [comment]
Thanks for raising this issue - that's a great point. There is not currently a license and that's an oversight rather than a deliberate choice.

I will need to do some digging into license types to compare Apache 2.0 against MIT (or others). Do you have any opinions on this from your experience?

**Comment by d-wasserman** [comment]
[GTFS is Apache 2](https://github.com/google/transit), but the [shared-streets-ref ](https://github.com/sharedstreets/sharedstreets-ref-system) seems to be MIT.

Generally, I don't recommend a copy-left license for a data specification, but to each their own. 

I personally prefer Apache 2 as it is still open, but [has more verbiage for legal edge cases](https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/).  To be consistent with the organization, I might prefer MIT in this case. That said, I don't know if MIT was chosen with serious consideration. My main concern with MIT is that it does not explicitly grant patent rights, so a patent troll could theoretically sue specification users, but that is speculative and beyond my understanding of law. I am no expert, just know enough to be dangerous.

**Comment by emilyeros** [comment]
After some research and discussions with @morganherlocker, here's where we landed:

Both Apache 2 and MIT are software licenses, whereas CurbLR is a specification, not software. So normally you would use a content oriented license, such as CC0. 

While there are cases of people licensing a spec with Apache or MIT, it's not really the intended purpose of those licenses. It looks like GTFS is actually dual-licensed with this distinction in mind; the content of the spec is CC0, but code included is Apache 2.

We'll use that model to make the content of CurbLR licensed under CC0, and the code licensed under MIT (consistent with the referencing system and SharedStreets' other software). 

To make this distinction, @morganherlocker tells me that it's acceptable to make a "frankenlicense" where we combine both into the same file with a bit of wrapper text to distinguish between content and code.

**Comment by d-wasserman** [comment]
Hi Emily, 
I agree.  It is under CC0 for the content relating to it, but I was initially asking for the license indicators that GitHub responds to (it signals intention to developers too for repo content). If you plan to mimic how GTFS Is licensed, then I have no further comments, as I find that is sufficient. In fact, it would be good to see how you cobble the licenses together so I can replicate it for the shared-row-spec. Thanks for diving a little deeper on this. 
David

**Comment by emilyeros** [comment]
Added CC0/MIT license, closing resolved issue. Thanks again for raising this.

**Comment by d-wasserman** [comment]
Nice, it calls out a license and still links to it in GitHub. This works.
