### ISSUE TITLE
Sweeping days regulations

### ISSUE THREAD

**Issue by joseflorido** [sharedstreets/CurbLR#3]
Is CurbLR supposed to support also street sweeping days regulations? If so, could you share an example of how to use it for this use case?

Thanks!

**Comment by emilyeros** [comment]
Yes, absolutely. A street sweeping regulation is really just a "no parking" zone that applies at a very specific timespan. You could include an optional reason if it were important to you to communicate the reason for the restriction. Here's an example for a hypothetical street sweeping restriction that applies between 11am and 1pm on the 2nd and 4th Tuesday of every month between April 1st and November 30th each year:


```
{
  "what": {
    "activity": "no parking",
    "reason": "street cleaning"
  },
 "priority": 3,
  "when": {
    "daysOfWeek": {
      "days": [
        "Tu"
      ],
      "occurrence_in_month": ["2nd", "4th"]
    },
    "timeOfDay": {
      "from": "11:00",
      "until": "13:00"
    },
    "effectiveDates": {
      "from": "04-01",
      "until": "11-30"
    }
  }
}

```
